/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["*[_ngcontent-%COMP%] {\n    font-family: 'Lilita One'\n}\n\nh1[_ngcontent-%COMP%] {\n    text-align: center;\n    position: relative;\n    top: 30px;\n    font-size: 70px;\n}\n\nform[_ngcontent-%COMP%] {\n    width: 70%;\n}\n.booking-container[_ngcontent-%COMP%] {\n\n}\n\n\n.jumbotron[_ngcontent-%COMP%] {\n    background-color: transparent;\n    margin-bottom: 0 !important;\n}\n\n.dropzone[_ngcontent-%COMP%] {\n    background: white;\n    border-radius: 5px;\n    border: 2px dashed rgb(0, 135, 247);\n    border-image: none;\n    height: 200px;\n    margin-left: auto;\n    margin-right: auto;\n}\n\ninput.ng-valid[_ngcontent-%COMP%], textarea.ng-valid[_ngcontent-%COMP%] {\n    border: 3px solid rgb(0, 255, 0);\n}\n\n.no-border[_ngcontent-%COMP%] {\n    border: 3px dotted rgb(0, 153, 255) !important;\n}\n\n\n\n.btn-submit[_ngcontent-%COMP%]{\n\n}\n\n@media (max-width: 480px) {\n    .booking-container[_ngcontent-%COMP%] {\n        margin-top: 100px;\n    }\n    }"];
export { styles as styles };
