/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".container[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n    position: relative;\n    margin-bottom: 20px;\n}\n\n.btn[_ngcontent-%COMP%] {\n   background:  linear-gradient(to bottom right, rgb(9, 9, 99), rgb(18, 11, 119)) !important;\n   color: white !important;\n}"];
export { styles as styles };
