/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["*[_ngcontent-%COMP%] {\n    color: black;\n    font-family: 'Lilita One';\n    font-size: 20px;\n    text-decoration: none;\n}\n\nfooter[_ngcontent-%COMP%] {\n    background-color:#ccc0ae;\n    height: 120px;\n    box-shadow:  0 0 25px #ccc;\n}\n\n.btn-social[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n    color: black;\n    display: inline-block;\n    margin: 30px 5px 0;\n    position: relative;\n    cursor: pointer;\n}\n\nfooter[_ngcontent-%COMP%]   div[_ngcontent-%COMP%] {\n}\n\n.copyright[_ngcontent-%COMP%] {\n    position: relative;\n    top: 25px;\n}\n\n\n@media (max-width: 991px) {\n\n    \n}"];
export { styles as styles };
