/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["div[_ngcontent-%COMP%] {\n    display: inline-block;\n}\n\n.btn-toggle[_ngcontent-%COMP%] {\n    cursor: pointer;\n    font-size: 40px;\n    top: -184px;\n    position: relative;\n}"];
export { styles as styles };
