/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".map-component[_ngcontent-%COMP%] {\n    height: 550px;\n    margin: 55px auto !important;\n}\n\nagm-map[_ngcontent-%COMP%] {\n    height: 450px;\n    width: 700px;\n    margin: 0 auto !important;\n}\n\n.map[_ngcontent-%COMP%] {\n    height: 400px;\n    width: 700px;\n    margin: auto auto;\n    position: relative;\n    border-radius: 15px !important;\n}\n\n.address[_ngcontent-%COMP%] {\n    position: relative;\n}\n\n.address-h[_ngcontent-%COMP%] {\n    font-size: 25px;\n}\n\n.address-p[_ngcontent-%COMP%] {\n    font-size: 20px;\n}\n\n@media (max-width: 953px) {\n    \nagm-map[_ngcontent-%COMP%] {\n    width: 400px;\n    margin: 0 auto;\n}\n\n.map[_ngcontent-%COMP%] {\n    width: 400px;\n}\n\n}\n\n\n\n@media (max-width: 480px) {\n    .address[_ngcontent-%COMP%] {\n        font-size: 20px;\n    }\n    agm-map[_ngcontent-%COMP%] {\n        width: 100%;\n        height: 385px !important;\n\n        }\n    \n    .map[_ngcontent-%COMP%] {\n        width: 100%;\n\n    }\n\n    .map-component[_ngcontent-%COMP%] {\n       \n        margin: 30px auto -20px !important;\n    }\n\n}"];
export { styles as styles };
