/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".list-group-item[_ngcontent-%COMP%] {\n    height: 100px;\n    color: black;\n    width: 400px;\n    margin: 0 auto;\n}\n\n.list-group-item.active[_ngcontent-%COMP%] {\n    color: black;\n    background-color: bisque;\n    border: none;\n}"];
export { styles as styles };
