/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".start-text[_ngcontent-%COMP%] {\n    margin-top: 180px;\n}"];
export { styles as styles };
