/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["*[_ngcontent-%COMP%] {\n    font-family: 'Lilita One'\n}\n\nh1[_ngcontent-%COMP%] {\n    text-align: center;\n    position: relative;\n    top: 30px;\n    font-size: 70px;\n}\n\n.gallery-container[_ngcontent-%COMP%] {\n    background-color: white;\n}\n\n\n\n\n\n.gallery[_ngcontent-%COMP%]   div[_ngcontent-%COMP%] {\n    display: inline-block;\n    margin: 80px 0 60px;\n}\n\n\n\n.jumbotron[_ngcontent-%COMP%] {\n    background-color: transparent !important;\n    margin-bottom: 0 !important;\n}\n\n.jumbotron-list[_ngcontent-%COMP%] {\n    background-color: bisque;\n    left: 100px;\n    padding: 50px;\n    z-index: 9999;\n}\n\n@media (max-width: 480px) {\n    .gallery-container[_ngcontent-%COMP%] {\n        margin-top: 100px;\n    }\n    }"];
export { styles as styles };
