/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["*[_ngcontent-%COMP%] {\n    font-family: 'Lilita One'\n}\n\nh1[_ngcontent-%COMP%] {\n    text-align: center;\n    position: relative;\n    top: 30px;\n    font-size: 70px;\n}\n\n.pricing-container[_ngcontent-%COMP%] {\n    background-color: white !important;\n}\n\n.pricing[_ngcontent-%COMP%]   *[_ngcontent-%COMP%] {\n    padding: 10px;\n}\n\n\n\n\n.details-btn[_ngcontent-%COMP%] {\n    background: linear-gradient(to bottom right, rgb(9, 9, 99), rgb(18, 11, 119)) !important;\n}\n\n.pricing[_ngcontent-%COMP%]   i[_ngcontent-%COMP%] {\n    font-size: 40px;\n}\n\n.pricing-content[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n    padding: 20px 0 0 0 !important;\n}\n\n.pricing-content[_ngcontent-%COMP%] {\n    box-shadow: 0 0 15px #ccc;\n    width: 250px;\n    margin: 0 auto;\n    height: 300px;\n}\n\n.jumbotron[_ngcontent-%COMP%] {\n    background-color: transparent;\n    margin-bottom: 0 !important;\n}\n\n@media (max-width: 991px) {\n    .pricing-container[_ngcontent-%COMP%] {\n        height: auto;\n    }\n}\n\n@media (max-width: 575px) {\n    .pricing-content[_ngcontent-%COMP%] {\n        margin: 30px auto 20px;\n    }\n}\n\n@media (max-width: 480px) {\n    .pricing-container[_ngcontent-%COMP%] {\n        margin-top: 100px;\n    }\n    }"];
export { styles as styles };
